version: '3.8'

services:
  sqlserver_v2:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_v2
    environment:
      SA_PASSWORD: "YourStrong!Password"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - mynetwork
    command: /opt/mssql/bin/sqlservr

  mssql_tools:
    image: mrlioncub/mssql-tools
    container_name: mssql_tools
    depends_on:
      - sqlserver_v2
    networks:
      - mynetwork
    entrypoint: /opt/mssql-tools/bin/sqlcmd -S sqlserver_v2 -U SA -P 'YourStrong!Password'
    # В данном случае мы напрямую вызываем sqlcmd, а не /bin/bash

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web_minicrm_app
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    ports:
      - "8080:80"
    depends_on:
      - sqlserver_v2
    networks:
      - mynetwork

networks:
  mynetwork:
